name: "ci-cd pipeline"

on: 
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install 
      - name: Build file
        run: npm run build
        env:
          CI: false
      

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          REACT_APP_API_BASE_URL : ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_OKTA_LOGIN_REDIRECT_PATH : ${{ secrets.REACT_APP_OKTA_LOGIN_REDIRECT_PATH }}
          REACT_APP_OKTA_CLIENT_ID : ${{ secrets.REACT_APP_OKTA_CLIENT_ID }}
          REACT_APP_OKTA_ISSUER : ${{ secrets.REACT_APP_OKTA_ISSUER }}
          REACT_APP_OKTA_ORG_URL : ${{ secrets.REACT_APP_OKTA_ORG_URL }}
          REACT_APP_OKTA_SCOPES : ${{ secrets.REACT_APP_OKTA_SCOPES }}
          REACT_APP_SENTRY_DSN : ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_SOCKET_URL : ${{ secrets.REACT_APP_SOCKET_URL }}
          build-dir: './build'
          comment-on-commit: true
